/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author laert
 */


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Model.DAO.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;


public class MainjanelaView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainjanelaView() {
        initComponents();
        
        Connection con = null;
        PreparedStatement stmt = null;

        try {
            con = Conexao.getConnection();
            List<String> strList = new ArrayList<String>();

            String query = "select * from cliente";
            stmt = con.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();

            while(rs.next()){
                strList.add(rs.getString("nome") + " " + rs.getString("sobrenome"));
            }
            stmt.close();
            con.close();
            DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(strList.toArray());
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteView1 = new View.ClienteView();
        clienteView3 = new View.ClienteView();
        clienteView2 = new View.ClienteView();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        clientesView1 = new View.ClienteView();
        clienteView5 = new View.ClienteView();
        manipularView1 = new View.ManipularView();
        contaView2 = new View.ContaView();
        manipularView3 = new View.ManipularView();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout clientesView1Layout = new javax.swing.GroupLayout(clientesView1);
        clientesView1.setLayout(clientesView1Layout);
        clientesView1Layout.setHorizontalGroup(
            clientesView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesView1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienteView5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientesView1Layout.setVerticalGroup(
            clientesView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesView1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienteView5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", clientesView1);

        javax.swing.GroupLayout manipularView1Layout = new javax.swing.GroupLayout(manipularView1);
        manipularView1.setLayout(manipularView1Layout);
        manipularView1Layout.setHorizontalGroup(
            manipularView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manipularView1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(contaView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        manipularView1Layout.setVerticalGroup(
            manipularView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manipularView1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contaView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conta", manipularView1);
        jTabbedPane1.addTab("Manipular", manipularView3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboContaActionPerformed
    }//GEN-LAST:event_jComboContaActionPerformed

    private void jButtonSalvarClienteContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarClienteContaActionPerformed
    }//GEN-LAST:event_jButtonSalvarClienteContaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.ClienteView clienteView1;
    private View.ClienteView clienteView2;
    private View.ClienteView clienteView3;
    private View.ClienteView clienteView5;
    private View.ClienteView clientesView1;
    private View.ContaView contaView2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private View.ManipularView manipularView1;
    private View.ManipularView manipularView3;
    // End of variables declaration//GEN-END:variables
}

